<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIT5zWxz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIT5zWxz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIT5zWxz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIT5zWxz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIT5zWxz\App_KernelDevDebugContainer([
    'container.build_hash' => 'IT5zWxz',
    'container.build_id' => '44ed5b6d',
    'container.build_time' => 1579940370,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIT5zWxz');
